services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 24212002
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  app:
    image: bojanajancheska/kiii-project:latest
    container_name: movies-project
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/movies
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 24212002
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
      SPRING_DATASOURCE_PLATFORM: postgres
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_LABEL_ENABLE: "true"
    command: --interval 30

volumes:
  postgres-data: